'use client';

import { motion } from 'framer-motion';
import { Brain, Target, BarChart3, BookOpen, TrendingUp, Award, Sparkles } from 'lucide-react';
import FeatureCard from '../ui/FeatureCard';

export default function FeaturesSection() {
    const features = [
        {
            icon: Brain,
            title: 'AI-Powered Resume Analysis',
            description:
                'Advanced NLP engine extracts skills, experience, and qualifications from your resume instantly with 95% accuracy.',
            badge: 'Smart Analysis',
        },
        {
            icon: Target,
            title: 'Personalized Career Roadmaps',
            description:
                'Get custom learning paths generated by AI, matched to your profile, goals, and industry requirements.',
            badge: 'Custom Paths',
        },
        {
            icon: BarChart3,
            title: 'Skill Gap Analysis',
            description:
                'Identify missing skills for your dream role and receive targeted recommendations to bridge the gap.',
            badge: 'Gap Analysis',
        },
        {
            icon: BookOpen,
            title: 'Smart Assessments',
            description:
                'Knowledge-based quizzes with instant feedback to track your progress and validate your expertise.',
            badge: 'Interactive',
        },
        {
            icon: TrendingUp,
            title: 'Real-Time Progress Tracking',
            description:
                'Centralized dashboard showing skill development, quiz results, and next steps in your career journey.',
            badge: 'Live Analytics',
        },
        {
            icon: Award,
            title: 'Certification Matching',
            description:
                'Semantic matching with courses and certifications using advanced NLP embeddings and transformers.',
            badge: 'Smart Match',
        },
    ];

    return (
        <section id="features" className="py-20 px-4 bg-gradient-to-b from-black to-white/5">
            <div className="max-w-7xl mx-auto">
                {/* Section Header */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="text-center mb-16"
                >
                    <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 border border-primary/20 rounded-full mb-6">
                        <Sparkles className="w-4 h-4 text-primary" />
                        <span className="text-sm font-medium text-primary">Our Features</span>
                    </div>
                    <h2 className="text-4xl lg:text-5xl font-bold mb-4">
                        Smarter Tools for <span className="text-primary">Learning & Upskilling</span>
                    </h2>
                    <p className="text-xl text-white/70 max-w-2xl mx-auto">
                        Everything you need to navigate your career path with confidence and precision
                    </p>
                </motion.div>

                {/* Features Grid */}
                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {features.map((feature, idx) => (
                        <FeatureCard key={idx} feature={feature} index={idx} />
                    ))}
                </div>
            </div>
        </section>
    );
}
